---
  - name: Create EC2 instance
    ec2:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      region: '{{ win_ec2_region }}'
      instance_type: '{{ win_ec2_instance_type }}'
      instance_tags:
          Name: '{{win_ec2_name_prefix}}'
      group: '{{ win_ec2_security_group }}'
      image: '{{ item_id }}'
      
...
    